In [1]:
import numpy as np

### 배열

- 생성

In [3]:
# 1차원 배열
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [4]:
# 2차원 배열
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
# 3차원 배열
c = np.array([[[1, 2, 3, 4]], [[5, 6, 7, 8]]])
c

array([[[1, 2, 3, 4]],

       [[5, 6, 7, 8]]])

- 배열 정보

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# 배열의 차원 = 행렬의 깊이
a.ndim

2

In [9]:
# 배열의 크기 (1,2차원 - 행, 열 / 3차원 - 깊이, 행, 열)
a.shape

(2, 3)

In [10]:
# 배열의 행 갯수
len(a)

2

In [11]:
# 배열의 열 갯수
a.shape[1]

3

In [12]:
# 배열 요소 갯수
a.size

6

- 연산

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 덧셈
print(a + b)

# 뺄셈    
print(a - b)

# 곱셈
print(a * b)

# 나눗셈
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


- 벡터화 연산

In [14]:
a = np.array([1, 2, 3])

# 덧셈
print(a + 1)

# 뺄셈    
print(a - 1)

# 곱셈
print(a * 2)

# 나눗셈
print(a / 2)

[2 3 4]
[0 1 2]
[2 4 6]
[0.5 1.  1.5]


- 인덱싱, 슬라이싱

In [15]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
# 첫번째 행(0)의 3번째 요소까지만 추출
a[0, :3]

array([1, 2, 3])

In [17]:
# 전체 행(:)의 뒤에서 1번째 요소들만 추출   
a[:, -1]

array([4, 8])

In [18]:
# 두번째 행(1)의 1번째 요소부터 끝까지 추출
a[1, 1:]

array([6, 7, 8])

In [19]:
# 전체 행(:)의 2번째 요소까지만 추출
a[:, :2]

array([[1, 2],
       [5, 6]])

- Boolean 인덱싱

In [20]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# 짝수만 추출
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

- 정수 인덱싱

In [22]:
a = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [23]:
# 3, 4, 5, 6 인덱스 요소 추출
a[[3, 4, 5, 6]]

array([13, 14, 15, 16])